[package]
name = "luna_engine"
version = "7.2.0"
edition = "2021"

[dependencies]
rand = "0.8"
rand_chacha = "0.3"
lazy_static = "1.4"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
strip = true
debug = false

[target.'cfg(target_arch = "x86_64")']
rustflags = ["-C", "target-cpu=native"]