[package]
name = "luna_ce"
version = "1.0.0"
authors = ["Daniele"]
edition = "2024"

[dependencies]
rand = "0.8"
rand_chacha = "0.3"  # Aggiungi questa
log = "0.4"          # Aggiungi questa
env_logger = "0.11"  # Aggiungi questa (solo per debug)

[features]
default = []
simd = []
nnue = []
embedded_nnue = []
evaluation = []  # Feature flag per evaluation

[profile.release]
lto = true
codegen-units = 1
opt-level = 3